### ISSUE TITLE
iOS 7 crash in v1.3

### ISSUE THREAD

**Issue by tomizimobile** [davbeck/TUSafariActivity#16]
The change in `TUSafariActivity.m`- line 54 
`return [UIImage imageNamed:@"TUSafariActivity.bundle/safari" inBundle:[NSBundle bundleForClass:self.class] compatibleWithTraitCollection:nil];` 
causes iOS 7 apps to crash, as that's an iOS 8 only method

**Comment by davbeck** [comment]
This should be fixed in 3728c1286d8b927b0cdc2d1669608c6e6f7184d2.
