### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mzgaljic** [davbeck/TUSafariActivity#24]
I am aggregating all of the license files from the 3rd party libraries in my app so that I can give proper attribution. This project does not have any license file at all.

Under what terms are you releasing this code? MIT License?

**Comment by davbeck** [comment]
I'm not sure what you mean. There is [LICENSE.md](https://github.com/davbeck/TUSafariActivity/blob/master/LICENSE.md) which has the full license agreement, the license field in the [podspec](https://github.com/davbeck/TUSafariActivity/blob/master/TUSafariActivity.podspec), and the license shield ([![License](https://img.shields.io/cocoapods/l/TUSafariActivity.svg?style=flat)](http://cocoadocs.org/docsets/TUSafariActivity)) in the README.

All of which are BSD.

**Comment by mzgaljic** [comment]
My apologies, my local copy of the project did not have the license file for some reason. I quickly skimmed through the readme.md yesterday and didn't spot any license information.

Looks like I need to be more thorough! Sorry about that.  :)
