### ISSUE TITLE
Xcode8.1 TUSafariActivity.bundle: bundle format unrecognized, invalid, or unsuitable.

### ISSUE THREAD

**Issue by lrsalway-here** [davbeck/TUSafariActivity#28]
log:
/Users/~/Library/Developer/Xcode/DerivedData/~-dntgqumvkjobpgeribbdngdujkvi/Build/Products/Debug-iphonesimulator/TUSafariActivity.bundle: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1

**Comment by mbodge** [comment]
Same issue.

**Comment by wxforgb** [comment]
I fixed this problem by Updating CocoaPods itself!
