### ISSUE TITLE
Please add support of SwiftPM

### ISSUE THREAD

**Issue by Exey** [davbeck/TUSafariActivity#33]
Please add Package.swift

**Comment by davbeck** [comment]
I would be happy to review a pull request adding this.

**Comment by c-villain** [comment]
@davbeck   any progress in addition of spm support?

**Comment by dhritzkiv** [comment]
One more step is needed before SPM is supported: the version needs to be bumped to 1.0.5 and a version tag created. 

Otherwise, the commits that added SPM support are not part of any version tag, and installing per the instructions in the README currently doesn't work.

**Comment by davbeck** [comment]
[Done](https://github.com/davbeck/TUSafariActivity/releases/tag/1.0.5)
