### ISSUE TITLE
SwiftPM: Icon not shown

### ISSUE THREAD

**Issue by herrernst** [davbeck/TUSafariActivity#39]
Thank you for providing a Swift Package. Unfortunately, the Safari icon is not displayed on the side of the label.

![Screenshot 2023-10-23 at 12 34 01](https://github.com/davbeck/TUSafariActivity/assets/20795/63e375c2-38f2-4408-ae57-b70b1343b826)

**Comment by davbeck** [comment]
Should be fixed in 1.0.6.
